#Usamos la base ligera compatible con multiples arquitecturas
FROM alpine:latest

#Instalamos una utilidad basica para probar
RUN apk add --no-cache curl 

CMD [ "echo", "Contenedor listo para correr en cualquier procesador" ]