#Cambiamos de node:18-alpine a una version moderna y parcheada 

FROM node:22-alpine 

WORKDIR /app

# un  comando para probar que funiona 

CMD [ "node", "-e","console.log('Contenedor seguro y oprimizado')" ]

